db:
  username: postgres
  password: 111
  pool.size: 12
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost, 127.0.0.1
  properties:
    first: 1
    last: 2
    key: value
  pool:
    size: 10
    timeout: 20
  pools:
    - size: 10
      timeout: 20
    - size: 10
      timeout: 20
    - size: 10
      timeout: 20

logging:
  level:
    root: INFO
    by.dre.spring.database.repository.pool.ConnectionPool: INFO
    by.dre.spring.config.JpaConfiguration: INFO
#  file:
#    name: by.dre
#    path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
#      hbm2ddl.auto: validate
  messages:
    basename: messages
app:
  image:
    bucket: D:\Java_dev\Java EE\spring-starter\images